# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jXmmZXJXfrG8vQRA6K859EkKqblNCN4Y
"""

# Definición de la clase abstracta
class Estudiante(ABC):
    def _init_(self, nombre, edad, grado):
        self.nombre = nombre
        self.edad = edad
        self.grado = grado

# Método obligatorio a ser implementado en las subclases
    @abstractmethod
    def mostrar_informacion(self):
        pass

# Subclase para estudiantes universitarios
class EstudianteUniversitario(Estudiante):
    def _init_(self, nombre, edad, grado, carrera):
        super()._init_(nombre, edad, grado) #Super es una función que permite llamar método de una clase padre
        self.carrera = carrera

    def mostrar_informacion(self):
        return f"Nombre: {self.nombre}, Edad: {self.edad}, Nivel: Universitario, Carrera: {self.carrera}, Semestre: {self.grado}"

#Subclase para estudiantes de secundaria
class EstudianteSecundaria(Estudiante):
    def mostrar_informacion(self):
        return f"Nombre: {self.nombre}, Edad: {self.edad}, Nivel: Secundaria, Grado: {self.grado}"

#Crear instancias de las subclases
universitario = EstudianteUniversitario("Carlos Pérez", 20, "5°", "Ingeniería de Sistemas")
secundaria = EstudianteSecundaria("Ana Gómez", 16, "10°")

# Mostrar la información de cada estudiante
print(universitario.mostrar_informacion())
print(secundaria.mostrar_informacion())

"""ejemplo 2"""

from abc import ABC, abstractmethod

class Metodopago(ABC):
    def _init_(self, nequi, daviplata, pse, tarjetacredito, tarjetadebito, efectivo):
        self.nequi = nequi
        self.daviplata = daviplata
        self.pse = pse
        self.tarjetacredito = tarjetacredito
        self.tarjetadebito = tarjetadebito
        self.efectivo = efectivo

    @abstractmethod
    def mostrar_informacion(self):
        pass

class MetodoDePago(Metodopago):
    def _init_(self, nequi, daviplata, pse, tarjetacredito, tarjetadebito, efectivo):
        super()._init_(nequi, daviplata, pse, tarjetacredito, tarjetadebito, efectivo)

    def mostrar_informacion(self):
        return f"los metodos de pago que ofecen son: {self.nequi}, {self.daviplata}, {self.pse}, {self.tarjetacredito}, {self.tarjetadebito}, {self.efectivo}"

metodo_pago = MetodoDePago("Nequi", "Daviplata", "PSE", "Visa", "MasterCard", "Efectivo")

print(metodo_pago.mostrar_informacion())